### ISSUE TITLE
Quick fix to PostsList component to handle undefined excerpts

### ISSUE THREAD

**Issue by lakebayagency** [josh-collinsworth/sveltekit-blog-starter#27]
Simple fix to skip rendering "undefined" if your post doesn't have an excerpt:

```javascript
{#if post.excerpt !== undefined}
	{post.excerpt}
{/if}
```

**Comment by josh-collinsworth** [comment]
Is there any reason not to just use this as the condition?

```svelte
{#if post.excerpt}
```

**Comment by lakebayagency** [comment]
Only my ignorance! 🙂

**Comment by josh-collinsworth** [comment]
After some consideration, I don't think this _should_ be fixed, since the excerpt data is also used by the meta tags present on the post pages. My feeling is that the project probably _shouldn't_ treat a frontmatter prop as optional when it goes into the SEO of the published site.

Naturally, it's just a starter and authors can remove it if they like. I think this should probably remain as the "happy path" for the time being, though.
