### ISSUE TITLE
Components don't render into built posts

### ISSUE THREAD

**Issue by lakebayagency** [josh-collinsworth/sveltekit-blog-starter#28]
I'm not currently able to render Svelte components inside of the posts that are pre-rendered at the build stage.

The postContent is compiled via an {@html data.postContent} tag, which seems to ignore the script and style tags and simply output the html.  Or maybe not quite that, but the end result is that the component isn't functional inside of these post pages, just displayed.

Here is my repo showing this:
https://github.com/lakebayagency/test-boinger

Boinger is a component from the mdsvex playground: https://mdsvex.com/playground

To see the problem in action, go to the home page and observe that the boinger works fine inside of this page, which is rendered using a <svelte:component> tag.

Click the link below that, which will take you to a post that also references the Boinger component, but doesn't actually work.

Not sure what possible solutions are.

**Comment by josh-collinsworth** [comment]
@lakebayagency I was able to solve this issue by:

1) Changing `src/routes/blog/[post]/+page.server.js` to just `src/routes/blog/[post]/+page.js` (i.e,. removing `.server` from the file name); and
2) Altering how the file exports the component and passes it through the `data` prop to mirror the homepage. (In the working version, `+page.js` passes `post.default`, without calling the render method. Then `+page.svelte` inserts  it as  `<svelte:component this={data.PostContent}/>`, instead of using `@html`.)

It seems `+page.server.js` files are not capable of passing components. I must not have realized it because I never had interactive components on the blog pages.

I don't have time at the moment to open a PR to see about fixing the issue on the base repo but I hope that helps.

[EDIT: I lied; I do have time. See the below PR.]

**Comment by lakebayagency** [comment]
Awesome! Works great! 👍🏾💪🏾🏆
