### ISSUE TITLE
NavBar missing from the display in the footer

### ISSUE THREAD

**Issue by teonbrooks** [josh-collinsworth/sveltekit-blog-starter#41]
Hey, I noticed that in your footer component, the MainNav component is listed there but it doesn't appear in the build. I recently updated the base of my blog on the latest commits, and I noticed that the MainNav component is now missing in my footer as well.

https://github.com/josh-collinsworth/sveltekit-blog-starter/blob/a0e50de4b6c065e165462d06e962b1d07a3d45e8/src/lib/components/Footer.svelte#L7

Any suggestions to fix this?

**Comment by josh-collinsworth** [comment]
Hey @teonbrooks — sorry, I probably broke that. Looks like the issue is: the `MainNav` component is set to only appear when the menu is open.

I just pushed a change that will make the items in the menu their own component, so _that_ component can be placed in the footer instead.

https://github.com/josh-collinsworth/sveltekit-blog-starter/commit/456314996b4ec4055108ed7c6ec67683e4570ae9
