### ISSUE TITLE
`rss.xml` return `404` in prod

### ISSUE THREAD

**Issue by piotrpdev** [josh-collinsworth/sveltekit-blog-starter#8]
[`rss.xml` returns a `404`](https://sveltekit-static-starter.netlify.app/api/rss.xml) ¯\_(ツ)_/¯

Could be an issue with Netlify, same happens on [mine](https://piotrp.dev/api/rss.xml). ([GitHub](https://github.com/piotrpdev/website/blob/680aa12ff5bd646f4391b5b9bade4acadfa81891/src/routes/api/rss.xml/+server.js))

Tried clearing cache and redeploying but same thing. Log says it gets generated so idk.
```
2:26:54 AM: .svelte-kit/output/server/entries/endpoints/api/rss.xml/_server.js                                 1.52 KiB
```

**Comment by josh-collinsworth** [comment]
@piotrpdev Thanks for reporting! This is a weird issue with SvelteKit (or maybe with the static adapter) where routes won't be rendered if they're not called from within a `load` function. It's like the app is unaware of them at build time unless they're actually called somewhere.

Previously, I had a random call to the RSS feed tucked away in a server route, just to make sure it rendered (not to do anything with the data). I apparently removed that by accident. Now it's back and the issue is fixed. 👍
